### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by Hi-Vis** [asiripanich/aurinapi#15]
The steps I was using successfully to download data through the aurin package are now resulting in an error with the notaurin package/new AURIN adp site.

Using the exact code on the notaurin README.md file to download the public toilets dataset (inputting my own Aurin API credentials), I would expect a 'public_toilets' data object to download and appear in my global environment.

`public_toilets<-aur_get("aurin:datasource-UQ_ERG-UoM_AURIN_DB_public_toilets")`

Instead, the following error is thrown: 

Downloading 'aurin:datasource-UQ_ERG-UoM_AURIN_DB_public_toilets'...
Warning in CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  :
  GDAL Error 1: HTTP error code : 404
Error: Cannot open "http://[REDACTED_CREDENTIALS]@openapi.aurin.org.au/wfs?service=wfs&version=1.0.0&request=GetFeature&srsName=EPSG%3A4326&outputFormat=application%2Fjson&typename=aurin%3Adatasource-UQ_ERG-UoM_AURIN_DB_public_toilets"; Check connection parameters.

I am using R 4.1.3

**Comment by Hi-Vis** [comment]
Thanks so much @asiripanich! I re-installed the package using #14 and the data is successfully downloading now.

**Comment by asiripanich** [comment]
@Hi-Vis thanks for reporting this. I will merge #14 to main soon.
